
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  GATLING_BASEURL:
  GATLING_NR_USERS:
  GATLING_MAX_DURATION:
  GATLING_RAMPUP_TIME:
  GATLING_NR_USERS_AT_ONCE:
  containerimagetag: '$(Build.SourceVersion)'
  containerregistry: 'nttcshowcase.azurecr.io'
  containerimagerepository: 'technologyconsulting-showcase-driver'
  containerregistrysericeconnection: 'acr-sc'      

stages:
- stage: Compose 
  displayName: Build image trough compose and run
  jobs:  
  - job: Compose
    displayName: Compose up
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      inputs:
        script: 'chmod +x bin/run.sh' 
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'
    - task: DockerCompose@0
      inputs:
        action: 'Push services'
        containerregistrytype: 'Container Registry'
        azureSubscriptionEndpoint: $(containerregistrysericeconnection)
        azureContainerRegistry: $(containerimagerepository)
        dockerComposeFile: '**/docker-compose.yml'
        tags: '$(containerimagetag)'
        includeLatestTag: true   