
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Compose
  displayName: Build image trough compose and run
  jobs:  
  - job: Compose
    displayName: Compose up
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      inputs:
        script: 'chmod +x bin/run.sh' 
  
    - task: DockerCompose@0
      inputs:
       containerregistrytype: 'Container Registry'
       dockerComposeFile: '**/docker-compose.yml'
       action: 'Run a Docker Compose command'
       dockerComposeCommand: 'up'         