version: '3'
services:
  gatling-runner:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest
    #command: -r ${AWS_REPORT_BUCKET}
    image: gatling-runner
    environment:
      - GATLING_BASEURL=http://supplierdomain-tc-showcase-prod.trafficmanager.net
      - GATLING_NR_USERS=1
      - GATLING_MAX_DURATION=1
      - GATLING_RAMPUP_TIME=10
      - GATLING_NR_USERS_AT_ONCE=1
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
   # logging:
    #  driver: awslogs
     # options:
      #  awslogs-group: /ecs/gatling-runner
       # awslogs-region: ${AWS_REGION}
        #awslogs-stream-prefix: gatling-runner
