app: 
  image:
    repository: novatec/technologyconsulting-showcase-driver
    tag:  
  appconfig:
    GATLING_BASEURL_SUPPLIERDOMAIN: 
    GATLING_BASEURL_ORDERDOMAIN: 
    GATLING_BASEURL_MANUFACTUREDOMAIN: 
    GATLING_NR_USERS: 
    GATLING_MAX_DURATION: 
    GATLING_RAMPUP_TIME:
    GATLING_NR_USERS_AT_ONCE:  
  scale:
    minReplica: 1
    maxReplicas: 1
  azureconfig:
    resourcegroup: 
